name: build-pr

on:
  pull_request:

jobs:
  code-style:
    uses: ./.github/workflows/code-style.yml

  unit-tests:
    uses: ./.github/workflows/test.yml

  android-build:
    uses: ./.github/workflows/android-build.yml
